// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTracker.Data;

#nullable disable

namespace WorkoutTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823034543_Add6WeekCycle")]
    partial class Add6WeekCycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("WorkoutTracker.Models.BodyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BodyParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "胸",
                            TrainingDaysPerWeek = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "背中",
                            TrainingDaysPerWeek = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "肩",
                            TrainingDaysPerWeek = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "脚",
                            TrainingDaysPerWeek = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "二頭",
                            TrainingDaysPerWeek = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "三頭",
                            TrainingDaysPerWeek = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "腹",
                            TrainingDaysPerWeek = 1
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmrapE1RM")
                        .HasColumnType("REAL");

                    b.Property<int>("AmrapRep")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmrapWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseTargetRpe")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("BodyPartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultSetCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAmrapTracked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ReferencePercent1RM")
                        .HasColumnType("REAL");

                    b.Property<string>("TargetRepRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightIncrement")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BodyPartId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 7.0,
                            BaseWeight = 175.0,
                            BodyPartId = 1,
                            DefaultSetCount = 3,
                            IsAmrapTracked = true,
                            Name = "ベンチプレス",
                            ReferencePercent1RM = 0.78600000000000003,
                            TargetRepRange = "4〜6",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 2,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 7.0,
                            BaseWeight = 220.0,
                            BodyPartId = 4,
                            DefaultSetCount = 3,
                            IsAmrapTracked = true,
                            Name = "スクワット",
                            ReferencePercent1RM = 0.78600000000000003,
                            TargetRepRange = "4〜6",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 3,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 7.5,
                            BaseWeight = 100.0,
                            BodyPartId = 3,
                            DefaultSetCount = 3,
                            IsAmrapTracked = true,
                            Name = "ミリタリープレス",
                            ReferencePercent1RM = 0.77400000000000002,
                            TargetRepRange = "5〜7",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 4,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 7.5,
                            BaseWeight = 150.0,
                            BodyPartId = 4,
                            DefaultSetCount = 2,
                            IsAmrapTracked = true,
                            Name = "ルーマニアンデッドリフト",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "5〜7",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 5,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 7.5,
                            BaseWeight = 190.0,
                            BodyPartId = 4,
                            DefaultSetCount = 3,
                            IsAmrapTracked = true,
                            Name = "ハイバースクワット",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "5〜7",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 6,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.0,
                            BaseWeight = 0.0,
                            BodyPartId = 1,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "インクラインダンベルプレス",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "8〜12",
                            WeightIncrement = 2.0
                        },
                        new
                        {
                            Id = 7,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 7.5,
                            BaseWeight = 110.0,
                            BodyPartId = 2,
                            DefaultSetCount = 4,
                            IsAmrapTracked = false,
                            Name = "ベントオーバーロウ",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "5〜7",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 8,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.0,
                            BaseWeight = 110.0,
                            BodyPartId = 2,
                            DefaultSetCount = 4,
                            IsAmrapTracked = false,
                            Name = "ラットプルダウン",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "8〜12",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 9,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.5,
                            BaseWeight = 0.0,
                            BodyPartId = 3,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "サイドレイズ",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "12〜20",
                            WeightIncrement = 1.0
                        },
                        new
                        {
                            Id = 10,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.5,
                            BaseWeight = 0.0,
                            BodyPartId = 1,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "ケーブルフライ",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "10〜15",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 11,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.5,
                            BaseWeight = 0.0,
                            BodyPartId = 6,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "ライイングトライセプスEX",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "10〜15",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 12,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.0,
                            BaseWeight = 0.0,
                            BodyPartId = 2,
                            DefaultSetCount = 5,
                            IsAmrapTracked = false,
                            Name = "チェストサポーテッドロウ",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "8〜12",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 13,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.5,
                            BaseWeight = 0.0,
                            BodyPartId = 4,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "レッグカール",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "10〜15",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 14,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.5,
                            BaseWeight = 0.0,
                            BodyPartId = 5,
                            DefaultSetCount = 4,
                            IsAmrapTracked = false,
                            Name = "インクラインダンベルカール",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "10〜15",
                            WeightIncrement = 1.0
                        },
                        new
                        {
                            Id = 15,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 9.0,
                            BaseWeight = 0.0,
                            BodyPartId = 4,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "レッグエクステンション",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "10〜15",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 16,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 7.5,
                            BaseWeight = 0.0,
                            BodyPartId = 1,
                            DefaultSetCount = 3,
                            IsAmrapTracked = true,
                            Name = "インクラインベンチプレス",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "5〜7",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 17,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.0,
                            BaseWeight = 0.0,
                            BodyPartId = 1,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "マシンチェストプレス",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "8〜12",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 18,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.5,
                            BaseWeight = 0.0,
                            BodyPartId = 3,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "リアデルトフライ",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "12〜20",
                            WeightIncrement = 1.0
                        },
                        new
                        {
                            Id = 19,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.5,
                            BaseWeight = 0.0,
                            BodyPartId = 6,
                            DefaultSetCount = 3,
                            IsAmrapTracked = false,
                            Name = "ケーブルプレスダウン",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "10〜15",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 20,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.0,
                            BaseWeight = 80.0,
                            BodyPartId = 4,
                            DefaultSetCount = 2,
                            IsAmrapTracked = false,
                            Name = "ブルガリアンスクワット",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "6〜8",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 21,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 8.0,
                            BaseWeight = 0.0,
                            BodyPartId = 2,
                            DefaultSetCount = 4,
                            IsAmrapTracked = false,
                            Name = "ワンハンドラットプル",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "10〜15",
                            WeightIncrement = 2.5
                        },
                        new
                        {
                            Id = 22,
                            AmrapE1RM = 0.0,
                            AmrapRep = 0,
                            AmrapWeight = 0.0,
                            BaseTargetRpe = 9.0,
                            BaseWeight = 0.0,
                            BodyPartId = 5,
                            DefaultSetCount = 4,
                            IsAmrapTracked = false,
                            Name = "ダンベルカール",
                            ReferencePercent1RM = 0.0,
                            TargetRepRange = "10〜15",
                            WeightIncrement = 1.0
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Models.ExerciseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rep")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rpe")
                        .HasColumnType("REAL");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("ExerciseRecords");
                });

            modelBuilder.Entity("WorkoutTracker.Models.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekInCycle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("WorkoutTracker.Models.WeekProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetRpe")
                        .HasColumnType("REAL");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WeekProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            RepRange = "",
                            TargetRpe = 7.0,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 1,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 3,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 1,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 3,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 1,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 1,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 2,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 1,
                            RepRange = "",
                            TargetRpe = 7.0,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 2,
                            RepRange = "",
                            TargetRpe = 7.0,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 2,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 3,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 2,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 3,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 2,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 2,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 2,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 2,
                            RepRange = "",
                            TargetRpe = 7.0,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 13,
                            ExerciseId = 3,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 14,
                            ExerciseId = 3,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 3,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 15,
                            ExerciseId = 3,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 16,
                            ExerciseId = 3,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 17,
                            ExerciseId = 3,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 2,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 18,
                            ExerciseId = 3,
                            RepRange = "",
                            TargetRpe = 7.0,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 19,
                            ExerciseId = 4,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 20,
                            ExerciseId = 4,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 2,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 21,
                            ExerciseId = 4,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 2,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 22,
                            ExerciseId = 4,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 2,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 23,
                            ExerciseId = 4,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 2,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 24,
                            ExerciseId = 4,
                            RepRange = "",
                            TargetRpe = 7.0,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 25,
                            ExerciseId = 5,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 26,
                            ExerciseId = 5,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 3,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 27,
                            ExerciseId = 5,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 28,
                            ExerciseId = 5,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 29,
                            ExerciseId = 5,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 2,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 30,
                            ExerciseId = 5,
                            RepRange = "",
                            TargetRpe = 7.0,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 31,
                            ExerciseId = 6,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 32,
                            ExerciseId = 6,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 33,
                            ExerciseId = 6,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 34,
                            ExerciseId = 6,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 35,
                            ExerciseId = 6,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 36,
                            ExerciseId = 6,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 37,
                            ExerciseId = 7,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 4,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 38,
                            ExerciseId = 7,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 39,
                            ExerciseId = 7,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 40,
                            ExerciseId = 7,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 4,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 41,
                            ExerciseId = 7,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 42,
                            ExerciseId = 7,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 43,
                            ExerciseId = 8,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 4,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 44,
                            ExerciseId = 8,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 45,
                            ExerciseId = 8,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 46,
                            ExerciseId = 8,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 4,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 47,
                            ExerciseId = 8,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 48,
                            ExerciseId = 8,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 49,
                            ExerciseId = 9,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 50,
                            ExerciseId = 9,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 51,
                            ExerciseId = 9,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 52,
                            ExerciseId = 9,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 53,
                            ExerciseId = 9,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 54,
                            ExerciseId = 9,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 55,
                            ExerciseId = 10,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 56,
                            ExerciseId = 10,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 57,
                            ExerciseId = 10,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 58,
                            ExerciseId = 10,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 59,
                            ExerciseId = 10,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 60,
                            ExerciseId = 10,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 61,
                            ExerciseId = 11,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 62,
                            ExerciseId = 11,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 63,
                            ExerciseId = 11,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 64,
                            ExerciseId = 11,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 65,
                            ExerciseId = 11,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 66,
                            ExerciseId = 11,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 67,
                            ExerciseId = 12,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 5,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 68,
                            ExerciseId = 12,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 69,
                            ExerciseId = 12,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 70,
                            ExerciseId = 12,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 71,
                            ExerciseId = 12,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 72,
                            ExerciseId = 12,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 73,
                            ExerciseId = 13,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 74,
                            ExerciseId = 13,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 75,
                            ExerciseId = 13,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 76,
                            ExerciseId = 13,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 77,
                            ExerciseId = 13,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 78,
                            ExerciseId = 13,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 79,
                            ExerciseId = 14,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 4,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 80,
                            ExerciseId = 14,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 81,
                            ExerciseId = 14,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 82,
                            ExerciseId = 14,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 4,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 83,
                            ExerciseId = 14,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 84,
                            ExerciseId = 14,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 85,
                            ExerciseId = 15,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 86,
                            ExerciseId = 15,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 87,
                            ExerciseId = 15,
                            RepRange = "",
                            TargetRpe = 10.0,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 88,
                            ExerciseId = 15,
                            RepRange = "",
                            TargetRpe = 10.0,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 89,
                            ExerciseId = 15,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 90,
                            ExerciseId = 15,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 91,
                            ExerciseId = 16,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 92,
                            ExerciseId = 16,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 3,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 93,
                            ExerciseId = 16,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 94,
                            ExerciseId = 16,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 95,
                            ExerciseId = 16,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 2,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 96,
                            ExerciseId = 16,
                            RepRange = "",
                            TargetRpe = 7.0,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 97,
                            ExerciseId = 17,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 98,
                            ExerciseId = 17,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 99,
                            ExerciseId = 17,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 100,
                            ExerciseId = 17,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 101,
                            ExerciseId = 17,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 102,
                            ExerciseId = 17,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 103,
                            ExerciseId = 18,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 104,
                            ExerciseId = 18,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 105,
                            ExerciseId = 18,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 106,
                            ExerciseId = 18,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 107,
                            ExerciseId = 18,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 108,
                            ExerciseId = 18,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 109,
                            ExerciseId = 19,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 110,
                            ExerciseId = 19,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 111,
                            ExerciseId = 19,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 112,
                            ExerciseId = 19,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 113,
                            ExerciseId = 19,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 114,
                            ExerciseId = 19,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 115,
                            ExerciseId = 20,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 2,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 116,
                            ExerciseId = 20,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 4,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 117,
                            ExerciseId = 20,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 4,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 118,
                            ExerciseId = 20,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 2,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 119,
                            ExerciseId = 20,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 4,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 120,
                            ExerciseId = 20,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 121,
                            ExerciseId = 21,
                            RepRange = "",
                            TargetRpe = 8.0,
                            TargetSets = 4,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 122,
                            ExerciseId = 21,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 123,
                            ExerciseId = 21,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 124,
                            ExerciseId = 21,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 4,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 125,
                            ExerciseId = 21,
                            RepRange = "",
                            TargetRpe = 8.5,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 126,
                            ExerciseId = 21,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 127,
                            ExerciseId = 22,
                            RepRange = "",
                            TargetRpe = 9.0,
                            TargetSets = 4,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 128,
                            ExerciseId = 22,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 129,
                            ExerciseId = 22,
                            RepRange = "",
                            TargetRpe = 10.0,
                            TargetSets = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 130,
                            ExerciseId = 22,
                            RepRange = "",
                            TargetRpe = 10.0,
                            TargetSets = 4,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 131,
                            ExerciseId = 22,
                            RepRange = "",
                            TargetRpe = 9.5,
                            TargetSets = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 132,
                            ExerciseId = 22,
                            RepRange = "",
                            TargetRpe = 7.5,
                            TargetSets = 2,
                            WeekNumber = 6
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Models.Exercise", b =>
                {
                    b.HasOne("WorkoutTracker.Models.BodyPart", "BodyPart")
                        .WithMany()
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyPart");
                });

            modelBuilder.Entity("WorkoutTracker.Models.ExerciseRecord", b =>
                {
                    b.HasOne("WorkoutTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTracker.Models.TrainingSession", "Session")
                        .WithMany("Records")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WorkoutTracker.Models.WeekProfile", b =>
                {
                    b.HasOne("WorkoutTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("WorkoutTracker.Models.TrainingSession", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
